Pre-deployment pull
feeduraddiction/yourtime-cosmetics-store pull request #1
Opened 2022-04-18 07:19 UTC by feeduraddiction

Added all the features.

2022-04-18 08:14 UTC, AlexChrks requested changes

2022-04-18 08:14 UTC, AlexChrks commented on pages/_app.tsx
> +let persistor = persistStore(store);
Если persistor не меняется, то луче юзать const

2022-04-18 08:14 UTC, AlexChrks commented on pages/api/goods.ts
> +  const db = client.db();
Паттерн 
```
const client = await MongoClient.connect(
    "mongodb+srv://feeduraddiction:Vjq1Gfhjkm2qwerty@cluster0.8swm7.mongodb.net/yourtime-cosmetics?retryWrites=true&w=majority"
  );
  const db = client.db();
```
повторяется в 13 файлах
возможно стоит вынести в отдельную функцию getDatabase
как думаешь?

2022-04-18 08:14 UTC, AlexChrks commented on pages/api/insertGoodCart.ts
> +// };
Этот коммент нужен здесь?

2022-04-18 08:14 UTC, AlexChrks commented on pages/api/orders.ts
> +  console.log(order, user);
думаю это лишнее

2022-04-18 08:14 UTC, AlexChrks commented on pages/api/updateCart.ts
> +// };
коммент можно убрать

2022-04-18 08:14 UTC, AlexChrks commented on pages/catalogue/[category]/[goodID]/index.tsx
> +}
Храни интерфейсы в отдельном файле

2022-04-18 08:14 UTC, AlexChrks commented on src/assets/svgs/NavIcons.tsx
> +}
интерфейсы в отдельный файл

2022-04-18 08:14 UTC, AlexChrks commented on src/components/Footer/FooterContent/index.tsx
> +    <Fragment>
почему не <></>?

2022-04-18 08:14 UTC, AlexChrks commented on src/components/Header/Search/SearchResults/SearchResult/index.tsx
> +}
Храни интерфейсы в отдельном файле

2022-04-18 08:14 UTC, AlexChrks commented on src/components/Header/UserWindow/index.tsx
> +        <Fragment>
Может <>?

2022-04-18 08:14 UTC, AlexChrks commented on src/components/Layout/index.tsx
> +}
интерфейсы в один файл

2022-04-18 08:14 UTC, AlexChrks commented on src/components/MainPage/AdvantagesSection/Avantage/index.tsx
> +}
интерфейсы в отд файл

2022-04-18 08:14 UTC, AlexChrks commented on src/components/OrdersListPage/index.tsx
> +  console.log(data);
console лишний

2022-04-18 08:14 UTC, AlexChrks commented on src/components/UI/Button/index.tsx
> +}
интерфейсы в отд файл

2022-04-18 08:14 UTC, AlexChrks commented on src/components/UI/Card/Backdrop/index.module.scss
> +// }
нам нужен этот файл?

2022-04-18 08:14 UTC, AlexChrks commented on src/components/UI/Card/CardText/index.tsx
> +}
интерфейсы в отд файл

2022-04-18 08:14 UTC, AlexChrks commented on src/components/UI/Card/index.tsx
> +}
интерфейсы в отд файл

2022-04-18 08:14 UTC, AlexChrks commented on styles/globals.scss
> +// }
Этот коммент нужен?

2022-04-18 08:39 UTC, feeduraddiction commented on pages/_app.tsx
> +let persistor = persistStore(store);
Пример из оф. документации.

https://redux-toolkit.js.org/usage/usage-guide#use-with-redux-persist

2022-05-05 11:48 UTC, alexeychrks approved these changes

2022-05-10 08:12 UTC, merged